CREATE USER alumnos IDENTIFIED BY "alum123"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

ALTER USER alumnos QUOTA UNLIMITED ON USERS;

GRANT "CONNECT" TO alumnos;
GRANT "RESOURCE" to alumnos;