alter session set "_ORACLE_SCRIPT"=true;
CREATE USER tester2 IDENTIFIED BY "tester"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

ALTER USER tester2 QUOTA UNLIMITED ON USERS;

GRANT "CONNECT" TO tester2;
GRANT "RESOURCE" TO tester2;
GRANT CREATE VIEW TO tester2;