alter session set "_ORACLE_SCRIPT"=true;
CREATE USER alumnos2 IDENTIFIED BY "alum123"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

ALTER USER alumnos2 QUOTA UNLIMITED ON USERS;

GRANT "CONNECT" TO alumnos2;
GRANT "RESOURCE" to alumnos2;
GRANT CREATE VIEW to alumnos2;